# Generated by Django 4.2.7 on 2023-11-16 08:40

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_show', '0001_initial'),
        ('car_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Локация')),
                ('year_foundation', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='Год основания')),
                ('buyer_amount', models.IntegerField(verbose_name='Количество покупателей')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='UniqueBuyersSuppliers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('car_dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_buyers_supplier_car_show', to='car_show.carshow', verbose_name='Автосалон')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_buyers_supplier', to='supplier.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Уникальный клиент поставщика',
                'verbose_name_plural': 'Уникальные клиенты поставщиков',
                'db_table': 'unique_buyers_suppliers',
            },
        ),
        migrations.CreateModel(
            name='SupplierCarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model_supplier_car_model', to='car_model.carmodel', verbose_name='Модель автомобиля')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_car_model', to='supplier.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Автомобиль поставщика',
                'verbose_name_plural': 'Автомобили поставщиков',
                'db_table': 'supplier_cars',
            },
        ),
    ]
