# Generated by Django 4.2.7 on 2023-11-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_show', '0001_initial'),
        ('car_model', '0001_initial'),
        ('action', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_action', to='supplier.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='actioncardealership',
            name='car_dealership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_show_action', to='car_show.carshow', verbose_name='Автосалон'),
        ),
        migrations.AddField(
            model_name='actioncardealership',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_show_car_model_action', to='car_model.carmodel', verbose_name='Модель автомобиля'),
        ),
    ]
