# Generated by Django 4.2.7 on 2023-11-16 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncardealership',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='actionsupplier',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Скидка'),
        ),
    ]
