# Generated by Django 4.2.7 on 2023-11-23 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('purchase_history', '0001_initial'),
        ('action', '0002_initial'),
        ('car_show', '0002_initial'),
        ('supplier', '0001_initial'),
        ('car_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModel',
            new_name='Car',
        ),
    ]
