# Generated by Django 4.2.7 on 2023-11-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_show', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealershipsupplierslist',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_list_supplier', to='supplier.supplier', verbose_name='Поставщик'),
        ),
    ]
