# Generated by Django 4.2.7 on 2023-11-29 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('car_show', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='cardealershipsupplierslist',
            name='car_dealership',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_list_car_show', to='car_show.carshow', verbose_name='Автосалон'
            ),
        ),
        migrations.AddField(
            model_name='cardealershipsupplierslist',
            name='supplier',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_list_supplier', to='supplier.supplier', verbose_name='Поставщик'
            ),
        ),
    ]
