# Generated by Django 4.2.7 on 2023-11-16 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_show', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshow',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='carshow',
            name='engine_capacity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(8.0)], verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='carshow',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='carshowmodel',
            name='model_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество автомобилей'),
        ),
    ]
