# Generated by Django 4.2.7 on 2023-11-17 07:48

import django.core.validators
from django.db import migrations, models
import uuid

from typing import List, Any


class Migration(migrations.Migration):
    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                (
                    'balance',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Баланс'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'db_table': 'buyer',
            },
        ),
    ]
