name: Test

on:
  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
      
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      
      - name: Get requirements
        run: |
          pipenv requirements --dev > dev-requirements.txt
          
      - name: Install dependencies
        run: |
          pip install -r dev-requirements.txt
      
      - name: Test with pytest
        run: pytest --junit-xml=test-results.xml
        env:
          ENGINE: django.db.backends.postgresql
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          HOST: localhost
          PORT: 5432
          TIME_ZONE: Europe/Moscow
          LANGUAGE_CODE: ru
          DEBUG: true
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results.xml
            test-results/**/*.xml
            test-results/**/*.json
        env:
          ENGINE: django.db.backends.postgresql
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          HOST: localhost
          PORT: 5432
          TIME_ZONE: Europe/Moscow
          LANGUAGE_CODE: ru
          DEBUG: true
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
      
      - name: Upload code coverage to codeclimate
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 9b1dadc89a947551e718cfcc06d848d385d920e7b9df591ea3e1aa6edf6b2352
        with:
          coverageLocations: |
            ${{github.workspace}}/src/coverage.xml:coverage.py
