name: Test

on:
  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
      
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          
      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Run the tests
        run: |
          pytest -v .
        env:
          DATABASE_URL: postgres://postgres:secret@localhost:5432/postgres
      
      - name: publish test results
        uses: phoenix-actions/test-reporting@v12
        if: always()
        with:
          name: Test results
          path: "junit-*.xml"
          reporter: java-junit
      
      - name: upload code coverage to codeclimate
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 9b1dadc89a947551e718cfcc06d848d385d920e7b9df591ea3e1aa6edf6b2352
        with:
          coverageLocations: |
            ${{github.workspace}}/src/coverage.xml:coverage.py
